language: node_js
node_js:
  - 12
cache:
  - npm
branches:
  only:
    - main
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN_2 # Set in the settings page of your repository, as a secure variable
  keep_history: true
  repo: dalice157/dalice157.github.io
  on:
    branch: main
install:
  - npm install
script:
  - npm test
